### ISSUE TITLE
Don't work on grafana 9.1

### ISSUE THREAD

**Issue by judzk** [netsage-project/netsage-sankey-panel#13]
Hi, i'm trying to use your plugin with the lastest version of grafana, but i don't see any flow chart only superposed values.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/26792639/200588536-9b098329-5703-4d0a-8903-254b08b08bc5.png">
Any idea ?
Thanks

**Comment by KatrinaTurner** [comment]
Hi @judzk ,
I do get the same error you have above when I try to use a random walk or time series data, but if I use non time series data in 9.1.x, it seems to work just fine.
Let me know if you have any other questions.
Thanks!

p.s. sorry for the super late reply!  I wasn't subscribed to updates for some reason!
