### ISSUE TITLE
Multi-level sankey panel for energy flow

### ISSUE THREAD

**Issue by MichalNguyen** [netsage-project/netsage-sankey-panel#16]
Hello,
I was trying to follow all steps, how to create this panel. I am using Flux with Grafana and cannt create multi-level diagram. 
Don't you have any advice how to create it?
What i got: 
![image](https://github.com/netsage-project/netsage-sankey-panel/assets/26553639/73678f2e-4135-44be-99eb-5c56b2fbedc3)
Here is data:
![image](https://github.com/netsage-project/netsage-sankey-panel/assets/26553639/cb642bcd-358d-423e-8d52-673ca7ee8282)

Grafana: 9.4.9

**Comment by KatrinaTurner** [comment]
Hi!  You will want another column of data to get the multi levels.   The table you have attached only has source and destination so it will only have those two levels and the value column will be used for line thickness.  Hope this helps!
