### ISSUE TITLE
Hover summary is popping under the  panel

### ISSUE THREAD

**Issue by Yusseiin** [netsage-project/netsage-sankey-panel#23]
Hi all,
in my dashboard ( Grafana v10.2.2 ) the hover summary is popping behind the panel
![immagine](https://github.com/netsage-project/netsage-sankey-panel/assets/103202144/849f1b77-404a-44e0-82c0-75c9e03b173f)
![immagine](https://github.com/netsage-project/netsage-sankey-panel/assets/103202144/74f32332-a35b-429f-8e0c-d0f5ee8e656f)
Can someone help me?

**Comment by iqbalaydrus** [comment]
I'm also experiencing this issue

**Comment by v0tti** [comment]
We are having the same problem.

**Comment by KatrinaTurner** [comment]
Sorry I'm just seeing this now! I noticed the same thing when we recently upgraded our Grafana instance and will be looking into it next week!

**Comment by KatrinaTurner** [comment]
This fix has been published to Grafana in v1.1.2.  Thanks all!
