### ISSUE TITLE
how can this be used with an elasticsearch datasource.

### ISSUE THREAD

**Issue by cosmos1978** [netsage-project/netsage-sankey-panel#5]
I am strugling to get anything out of this using an elasticsearch datasource.

could you give an example ?

**Comment by KatrinaTurner** [comment]
Hi! Sorry for the late response.  
<img width="879" alt="Screen Shot 2022-05-12 at 8 46 56 AM" src="https://user-images.githubusercontent.com/46706381/168146866-bbc1f19d-dd55-49ed-b546-260ca018937b.png">

I hope this helps!  Let me know if you have other questions!
